[project]
name = 'clari-bounty'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.arbitrator]
path = 'contracts/arbitrator.clar'
clarity_version = 3
epoch = 3.1

[contracts.badge-nft]
path = 'contracts/badge-nft.clar'
clarity_version = 3
epoch = 3.1

[contracts.bounty-registry]
path = 'contracts/bounty-registry.clar'
clarity_version = 3
epoch = 3.1

[contracts.escrow]
path = 'contracts/escrow.clar'
clarity_version = 3
epoch = 3.1

[contracts.governance]
path = 'contracts/governance.clar'
clarity_version = 3
epoch = 3.1

[contracts.reputation]
path = 'contracts/reputation.clar'
clarity_version = 3
epoch = 3.1

[contracts.staking]
path = 'contracts/staking.clar'
clarity_version = 3
epoch = 3.1

[contracts.utils]
path = 'contracts/utils.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
